### ISSUE TITLE
How to use? Import not working

### ISSUE THREAD

**Issue by Loosie94** [andymantell/node-wpautop#6]
Hi, I was looking for exactly this function! 
I know this repo is a bit old, but this is what I need.
But somehow I can't make this work in a Nuxt 3 (Vue.js) Nuxt envirionment.

I use: 
`import { wpautop } from "wp`
`{{ wpautop('test') }}`

Any idea what I'm doing wrong?
Thanks!

**Comment by Loosie94** [comment]
Got this working with: `import wpautop from "wpautop/lib/wpautop.js";`
Thanks!

**Comment by andymantell** [comment]
Glad you got it working! Not sure why it didn't work like that without digging into it, but I think when I wrote it no-one was using `import` - I only ever tried `require` with this library.

Might be worth checking whether wordpress has made changes since this library was released though? It's nearly 10 years old!
